---
# Setup variables
- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install.
- include: "{{ ansible_os_family }}.yml"

# Set version.
- name: Get redis version.
  shell: redis-server --version
  register: redis_version_register
  changed_when: false

- name: Set redis version.
  set_fact:
    redis_version: "{{ redis_version_register.stdout | regex_replace('^.+ v=(.+?) .+$', '\\1') }}"

- name: Set redis major version.
  set_fact:
    redis_major_version: "{{ redis_version | regex_replace('^(.+?)\\..*$', '\\1') }}"

# Set redis.
- name: Copy redis configuration in place.
  template:
    src: "redis.conf.v{{ redis_major_version }}.j2"
    dest: "{{ redis_conf_file_path }}"
    owner: "{{ redis_owner }}"
    group: "{{ redis_group }}"
    mode: 0644
  notify:
    - restart redis

- name: Ensure redis is started and enabled to start at boot.
  service:
    name: redis
    state: started
    enabled: yes
