---
# Setup variables
- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
# Install.
- include: "{{ ansible_os_family }}.yml"

# Setup redis.
- name: Copy redis configuration in place.
  template:
    src: "{{ redis_conf_template }}"
    dest: "{{ redis_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - restart redis
